Multiple issues on workspace summary tab (no JIRA)
broadinstitute/firecloud-ui pull request #1253
Opened 2018-03-29 20:07 UTC by MattPutnam

1. The summary tab, like all tabs, requests a workspace refresh upon loading. This bubbles up to a containing component, then trickles back down as a props change. Previously, the workspace tab component was too aggressively refreshing when props changed. The result was that if you clicked "Edit" immediately as it became available, the refresh could reload the page. Selenium tests do exactly this, so they were failing sporadically on tests that edit things.
2. The tests regarding the rendering of links in the workspace attributes table were broken. The dos links resolve before creating a popup, so there needed to be a wait in that case.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2018-03-29 21:36 UTC, MattPutnam commented
jenkins retest

2018-03-30 13:21 UTC, dvoet commented
please run tests on this several times before merging

2018-03-30 13:48 UTC, UrsaStutsman commented
This looks good to me. But definitely should do multiple runs as Doug suggested.

2018-03-30 14:16 UTC, aweng98 commented
I recommend additional changes that I'd like to include in this PR.

Editing `WorkspaceMethodConfigDetailsPage.scala`

``` 
private val cancelEditedButton = Button("cancel-edit-method-config-button")

def openEditMode(expectSuccess: Boolean = true): Unit = {
    openEditModeButton.doClick()
    if (expectSuccess) {
      saveEditedMethodConfigButton.awaitEnabledState()
      cancelEditedButton.awaitEnabledState()
      saveEditedMethodConfigButton.awaitVisible()
    }
  }

  def saveEdits(expectSuccess: Boolean = true): Unit = {
    // The button can sometimes scroll off the page and become unclickable. Therefore we need to scroll it into view.
    saveEditedMethodConfigButton.scrollToVisible()
    saveEditedMethodConfigButton.doClick()
    if (expectSuccess) {
      openEditModeButton.awaitEnabledState()
      openLaunchAnalysisModalButton.awaitVisible()
    }
  }

```

2018-03-30 15:32 UTC, MattPutnam commented
1 success. Jenkins retest

2018-03-30 16:49 UTC, MattPutnam commented
fiab-start failed. Jenkins retest

2018-03-30 17:59 UTC, MattPutnam commented
Legit test failure

2018-03-30 18:36 UTC, MattPutnam commented
fiab-start failed. Jenkins retest

2018-03-30 18:59 UTC, MattPutnam commented
fiab-start failed. Jenkins retest

2018-03-30 20:17 UTC, MattPutnam commented
1 success (since new commit). Jenkins retest

2018-03-30 21:26 UTC, MattPutnam commented
2 failures, seemingly unrelated. 1 billing creation 400, 1 failure to click the "Launch analysis" button.

Jenkins retest

2018-04-02 11:10 UTC, dvoet requested changes
I don't see how this fixes the problem. And the last test failed with a "Tried to add workspace attribute while not editing" error too.

2018-04-02 18:04 UTC, MattPutnam commented
fiab-start failure

jenkins retest

2018-04-02 20:10 UTC, aweng98 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/page/workspaces/summary/WorkspaceSummaryPage.scala
>      !sidebar.editButton.isVisible
It'd be a better verification if this is checking for `sidebar.cancelButton` and `saveButton` visible. Correctly verifying expected UI elements displayed.

2018-04-02 22:47 UTC, MattPutnam commented
2 unrelated failures, submissions didn't complete

2018-04-02 23:29 UTC, dvoet commented
@MattPutnam can you please break out the most recent set of fixes into its own PR. I am not convinced the rest of it is worth doing given it didn't actually solve the problem. If it ends up being a good refactor, great, we can roll it out after the freeze is lifted. But for now let's keep changes to a minimum.

2018-04-03 15:36 UTC, MattPutnam commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/page/workspaces/summary/WorkspaceSummaryPage.scala
> -      sidebar.saveButton.scrollToVisible()
Clickable.doClick() already scrolls to visible

2018-04-03 15:37 UTC, MattPutnam commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/page/workspaces/summary/WorkspaceSummaryPage.scala
> -      awaitReady()
clickSave() already calls awaitReady()

2018-04-03 15:41 UTC, MattPutnam commented
@dvoet One of the reasons we're in this hell is because it's too easy to write broken tests. My refactors are all about making it easier to write correct test code. All of these changes are about making the code simpler and more correct at the same time. If I back out the refactors we're just making this codebase worse.

2018-04-03 16:19 UTC, aweng98 commented
I think Matt is on right path. Tests are easily broken are mainly due to brittle Page and framework methods. Brittle methods need to be fixed.

2018-04-03 18:43 UTC, MattPutnam commented
1 PreviewSpec failure that seems to be expected.

2018-04-03 22:38 UTC, aweng98 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/page/workspaces/summary/WorkspaceSummaryPage.scala
> +    await ready previewModal
style-nit: parentheses are used every where, but not here in `previewModal`

2018-04-03 22:44 UTC, aweng98 approved these changes
I don't find anything wrong with test code. I can't comment on UI react code because don't understand them. This PR looks good to me.

2018-04-03 22:49 UTC, aweng98 commented
if I may, can you consider rework `Collapse.ensureCollapsed` and `ensureExpanded` methods to something similar to below. let me know if you have question about why.
```
  def ensureCollapsed2(): Unit = {
    await condition {
      awaitReady()
      click on toggleComponent
      stateOf(toggleComponent) == "collapsed"
      // maybe a very very small sleep here
    }
  }
```

2018-04-04 13:14 UTC, dvoet approved these changes

2018-04-04 13:30 UTC, merged