abstract class `UISpec`: use in UI automation test suites
broadinstitute/firecloud-ui pull request #1294
Opened 2018-05-11 15:56 UTC by aweng98

All or most tests in test suite need a new billing project, we can avoid boilerplate of the loan-fixture method approach by using a fixture.Suite and overriding withFixture(OneArgTest).
Each test in a suite takes a billing-project fixture as a parameter, then pass the fixture into the test. This billing-project fixture method is responsible for claiming a clean billing project from GPAllocator in `beforeAll`, and clean up after in `afterAll`

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2018-05-11 19:35 UTC, aweng98 commented
jenkins retest

2018-05-11 23:05 UTC, aweng98 commented
jenkins retest

2018-05-11 23:08 UTC, aweng98 commented
jenkins retest

2018-05-14 16:20 UTC, aweng98 commented
jenkins retest

2018-05-14 16:50 UTC, aweng98 commented
fiab start failed

jenkins retest

2018-05-14 17:14 UTC, breilly2 requested changes
Seems fine but just looking for a couple of minor changes. Let me know if you have any questions.

2018-05-14 17:14 UTC, breilly2 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/fixture/UISpec.scala
> +  case class projectOwnerFixture(billingProject: String)
Since you only have one object in the fixture, I think you don't actually need the case class; you can just use the billing project name as the fixture object (using `String` for the `FixtureParam` type).

If you want to keep it, then 2 things:
1. Should probably be called something like `BillingProjectFixture`
2. Nit: Classes, including case classes, should start with a capital letter.

2018-05-14 17:14 UTC, breilly2 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/fixture/UISpec.scala
> +  override def beforeAll(): Unit = {
Using `BeforeAndAfterAll` changes the lifecycle of the claimed project. Maybe it's not a problem for `DataSpec` but I want to make sure that you considered that.

It's also potentially inconvenient that tests do not have control over the lifecycle. An alternative would be for this abstract class to define an abstract function for getting the billing project to provide to the test case. That way the extending suite can choose whether to use `BeforeAndAfter`/`BeforeAndAfterEach`/`BeforeAndAfterAll`.

2018-05-14 17:14 UTC, breilly2 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/fixture/UISpec.scala
> +abstract class UISpec extends fixture.FreeSpec with BeforeAndAfterAll with BillingFixtures with Matchers
Nit: I think `UISpec` is too general of a name for the very specific thing this class is doing. I'm having trouble coming up with a good alternative, though... maybe `BillingFixtureSpec`?

2018-05-15 16:31 UTC, aweng98 commented
@breilly2 review feedbacks addressed. thank you.

2018-05-15 18:03 UTC, aweng98 commented
unrelated: a flaky test `MethodLaunchSpec` failed on launch analysis

jenkins retest

2018-05-16 14:58 UTC, breilly2 approved these changes
👍 Looks good!

2018-05-16 15:13 UTC, merged