Jw googlelinks
broadinstitute/firecloud-ui pull request #529
Opened 2016-10-13 18:27 UTC by jlmwhitt

GAWB-991 Link to Google Cloud Console storage browser from monitor view

2016-10-13 21:34 UTC, davidangb commented
The summary tab for a workspace also links to the workspace's bucket. Could you centralize that link onto your new moncommon/google-cloud-context as well?

See https://github.com/broadinstitute/firecloud-ui/blob/develop/src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs#L180

2016-10-14 12:56 UTC, jlmwhitt commented
Summary tab has been updated as suggested

2016-10-14 17:56 UTC, dmohs requested changes
Great PR! Needs a couple of very minor tweaks. Feel free to get more details from me as needed.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
> +  {:refresh-workspace
Please update your editor to remove trailing whitespace. A few of the "edits" in this PR are just the addition of trailing whitespace.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
> +                         bucketName (:bucketName props)
These first two can be shortened by using destructuring:
```clojure
{:keys [submission-id bucketName]} props
```
Use your own judgement as to whether that concision adds value.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
> +                     :href (str moncommon/google-cloud-context bucketName "/" submission-id  "/" workflowName "/" workflowId "/" )
Nit: Whitespace before closing paren is inconsistent with style.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs
> +           workspace (:workspace props)
Seems like you don't need workspace here.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
> +
More idiomatic:
```clojure
(defn- workflow-name [callName]
  (let [names (string/split callName ".")]
    (first names)))
```
or just:
```clojure
(defn- workflow-name [callName]
  (first (string/split callName ".")))
```

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
> +    js/return (rest names);
`rest` returns a list. Are you sure that is what you want?

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
> +       (let [workflowName (workflow-name (:label props)) callName (call-name (:label props))]
Nits: `workflow-name` is more idiomatic for Clojure. We usually put each variable on its own line.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
> +                     :href (str moncommon/google-cloud-context (:bucketName props) "/" (:submission-id props)  "/" workflowName "/" (:workflowId props) "/" callName "/" )
Style nits: line length and trailing parens/brackets

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
>      [org.broadinstitute.firecloud-ui.page.workspace.monitor.common :refer [all-success? any-running? any-failed?]]
Can add the `:as` to this line if you want.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
> +           workspace (:workspace props)
This isn't used since the next line pulls it out of state.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
> +                         inputNames (string/split inputs ".")
`input-names` would be more idiomatic.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
> +                         workflowId (workflow "workflowId")]
By contrast, this one is a judgement call, since it may make sense sometimes to use camel case to match the JSON variable name.

2016-10-14 17:56 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs
> +           workspace (:workspace props)
This smells like a DRY violation to me. Does `workspace` have an ID? If so, what would the behavior be if that was different than the value in `workspace-id`?

2016-10-17 20:15 UTC, dmohs approved these changes
Looks great!

2016-10-17 20:15 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
> +      [clojure.string :as string]
We like to alphabetize these so we don't ever have to think about the order.

2016-10-17 20:15 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
> +    [clojure.string :as string]
Ditto.

2016-10-18 14:43 UTC, merged