Iz column defaults gawb 1140
broadinstitute/firecloud-ui pull request #547
Opened 2016-10-31 19:04 UTC by zarsky-broad

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-10-31 20:04 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/persistence.cljs
> +    (if (some-> saved-state validator)
Somehow this is working, but this really needs to be

```
(if (and validator (some-> saved-state validator))
```

in case validator doesn't exist.

2016-10-31 20:05 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
> +  (into {} (map (juxt key identity) m)))
Name suggestion: `index-by-key`

2016-10-31 20:09 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
> +  (into {} (map (juxt key identity) m)))
Or even just `index-by`.

2016-10-31 20:33 UTC, zarsky-broad commented
@MattPutnam fixed and fixed.

2016-11-01 18:33 UTC, dmohs requested changes
I'm seeing errors in my console starting at `org$broadinstitute$firecloud_ui$common$table$select_persistence_keys`. I'll re-review when things are working again.

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/entity_table.cljs
> +    [org.broadinstitute.firecloud-ui.utils :as utils]))
FYI: The reason we leave this is so you can add a new import without seeing a two-line change in git.

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
> +(defn select-persistence-keys [atom]
Should this be private (`defn-`)? I'd also recommend against binding a reserved word (`atom`).

What if you did:
```clojure
(def persistence-keys #{:column-meta :query-params :filter-group-index})
```

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
> +                :validator (fn [stored-value] (= (set (keys stored-value)) #{:column-meta :filter-group-index :query-params}))
You could use `persistence-keys` here.

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
> +     (swap! locals assoc :initial-state (select-persistence-keys @state))
And you could do `(select-keys @state persistence-keys)` here.

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +     ;(js* "debugger;")
To share this knowledge without leaving cruft in the code, might be cool to make a utility function.

2016-11-01 18:33 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
> +  (into {} (map (juxt key identity) m)))
Maybe configure your editor to include newlines at the end.

2016-11-01 18:42 UTC, zarsky-broad commented on src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
> +  (into {} (map (juxt key identity) m)))
Ah, my bad

2016-11-01 18:42 UTC, zarsky-broad commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +     ;(js* "debugger;")
Oop, didn't mean to leave this in...

2016-11-01 18:43 UTC, zarsky-broad commented on src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
> +                :validator (fn [stored-value] (= (set (keys stored-value)) #{:column-meta :filter-group-index :query-params}))
I don't _think_ that works here, we need a list of keys and that gets the values.

2016-11-01 19:03 UTC, zarsky-broad commented
@dmohs All addressed.

2016-11-07 22:09 UTC, dmohs submitted a review, later dismissed
Invalid input in the attribute causes the data tab to fail to render. Code looks good.

2016-11-07 22:09 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
> +                (fn [] (let [processed-columns (if-let [defaults (:column-defaults props)]
When things start pushing to the right margin like this it might be worth pulling this out into a function.

2016-11-14 21:22 UTC, dmohs requested changes
I think your change conflicted with Doug's.
![screen shot 2016-11-14 at 4 20 34 pm](https://cloud.githubusercontent.com/assets/1545444/20283269/4e6edd10-aa86-11e6-8eae-64cb25ea1e05.png)

2016-11-14 21:50 UTC, dmohs approved these changes
👍

2016-11-14 21:55 UTC, merged