GAWB-1126
broadinstitute/firecloud-ui pull request #577
Opened 2016-11-18 23:13 UTC by skwalker

Can use with this WIP orch branch https://github.com/broadinstitute/firecloud-orchestration/tree/skw_1126 (it just needs to be updated with config stuff). 

I think that select2 matches our UI better than the twitter typeahead, but both use jquery, and Isaac had used select2 before and suggested using that, which is why I did. I don't think there's anything that twitter typeahead could give us that is missing from select2, but if we think we should switch to that, that's okay.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-11-22 00:54 UTC, davidangb requested changes
I have a few comments inline, but my biggest concern is that this code is written very specifically for the diseaseOntology attribute, the DOID ontology, and will only work with one instance of typehead. This should be made more generic and schema-driven instead of tightly coupled to that specific property.

2016-11-22 00:54 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                                          :style {:width "100%"}}]
what happens if there are two attributes with typeahead? They'd both be looking for the ref `duos-typeahead`.

2016-11-22 00:54 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +    (if (= property-key :library:diseaseOntology) [:span {:style {:fontStyle "italic"}} (str " (DOID: " (style/url-to-doid (get library-attributes :library:diseaseOntologyDOID)) ")")])]])
this shouldn't look specifically for a property named "diseaseOntology" - it should be looking for any property enabled for ontology typeahead. Similarly, once we use another ontology, the "DOID_" prefix will be invalid.

2016-11-22 00:54 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +           primary-properties [:library:numSubjects :library:datatype :library:dataUseRestriction :library:diseaseOntology] ;; TODO replace with new field from schema
arggg these really should be in the schema, not cljs (see GAWB-1234)

2016-11-22 00:54 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                                  (aget obj "definition") "</div>"))))
this might be the only place we're using HTML directly, instead of cljs. Could this be refactored into cljs?

2016-11-22 19:08 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                       :escapeMarkup (fn [markup] markup)
`(fn [markup] markup)` -> `identity`

2016-11-22 19:08 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +  :diseaseOntologyDOID doid)
This needs to be inside the `case`, otherwise you're dropping everything on the floor and just returning `doid` no matter what.

2016-11-22 19:08 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
> +  (second (clojure.string/split url #"DOID_")))
This shouldn't be in style, maybe common?

2016-11-22 19:08 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +           primary-properties [:library:numSubjects :library:datatype :library:dataUseRestriction :library:diseaseOntology] ;; TODO replace with new field from schema
I'll end up taking care of that in GAWB-1130.

2016-11-22 20:20 UTC, skwalker commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                                  (aget obj "definition") "</div>"))))
Uhh I don't think that's possible... The select2 doesn't know how to go from cljs to html and I know this is kinda gross but I'm not sure how to change it..

2016-11-22 23:20 UTC, davidangb reviewed
PR works for me. I'm requesting addition of a few TODO comments in relevant places of the code, to make it easier later. Also, anywhere we're not talking specifically about the phenotype attribute specifically, try to use generic variable names like "id" instead of something like "doid".

Other than those - hopefully quick - changes, 👍

2016-11-22 23:20 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/common.cljs
> +   (str "DOID: " (second (clojure.string/split url #"DOID_"))))
add a TODO comment: when we support multiple ontologies, we'll need to look for some string other than "DOID".

2016-11-22 23:20 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +      [:span {:style {:fontStyle "italic"}} (str " (" (common/url-to-doid (get library-attributes :library:diseaseOntologyDOID)) ")")])]])
add a TODO comment: when we support multiple ontology-driven properties, can't hardcode the property name here.

2016-11-22 23:20 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                      (str (config/api-url-root) "/duos/autocomplete/" (aget params "term")))
add a TODO comment: when we support multiple ontologies, may need a different endpoint.

2016-11-22 23:20 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                                     (= typeahead "ontology") (:ontologyText @state)
add a TODO comment: when we support multiple ontology-driven properties, can't rely on hardcoded values in state.

2016-11-22 23:20 UTC, davidangb commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/library.cljs
> +                                         (swap! state assoc :ontologyText label :ontologyDOID id))))))))})
add a TODO comment: when we support multiple ontology-driven properties, can't hardcode the keys in state or attributes

2016-11-23 18:36 UTC, davidangb commented
👍 haven't tested functionally but code looks correct.

2016-12-12 04:44 UTC, closed without merging