Jw gawb 1290, 1289 display attributes and attributes of references
broadinstitute/firecloud-ui pull request #598
Opened 2016-12-07 21:12 UTC by jlmwhitt

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-12-08 19:54 UTC, jmthibault79 commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +  (cond (= (str entity-type) "sample_set") "Sample"
What knowledge does the UI have of the data model?  If that is available somewhere, we should use it here as well.  That would also give us e.g. Sample -> Participant relationships.

2016-12-08 20:12 UTC, jmthibault79 commented on src/cljs/org/broadinstitute/firecloud_ui/common/entity_table.cljs
> +                                                    (cond (= (str selected-entity-type) ":sample_set") (str (count items) " samples")
After this change, we don't list the samples here.  Is that what we want?

PO decision, I can see arguments for either way.  I just didn't see this change in the story.

2016-12-09 14:36 UTC, jlmwhitt commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +  (cond (= (str entity-type) "sample_set") "Sample"
I have updated so that the entity references in the main table are linked

2016-12-09 22:08 UTC, jmthibault79 commented
*** NOTE ***

I attempted to clean up this branch after some merge conflicts.  It is VERY LIKELY that some code that doesn't belong here has come along for the ride.  Please review this carefully.

See you in January!

2016-12-14 19:10 UTC, dmohs requested changes
`EntityAttributes` is swapping the state of its parent. I know it's not your fault, but we gotta fix it.

2016-12-14 19:10 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +(defn- is-single-ref? [attr-value]
This is duplicated in `entity_table.cljs` so should be pulled out into a common location.

2016-12-14 19:10 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/common/entity_table.cljs
> +                                               (if (:linked-entity-renderer props)
```clojure
(if-let [r (:linked-entity-renderer props)]
  (r attr-value)
  (:entityName attr-value))
```

2016-12-14 19:10 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +                            (if (map? x)   ;;map is a sample_set or pair_set or participant_set
Nit: The convention is usually single-semicolon comments for those that appear on the same line as code, double-semicolon for comments that are alone on a line.

2016-12-14 19:10 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +                             :attr-list attributes :mainState state}])]
`:mainState state`

2016-12-22 18:59 UTC, dmohs approved these changes
Thanks for taking the time to clean this up.

2016-12-22 20:50 UTC, zarsky-broad commented
(This last commit done w/ @dmohs, who says he approves, so I'm totally following procedure if anybody asks, which they likely won't, but it's the last day before the holiday break so I'm writing this here anyway; hello, posterity)

2016-12-22 20:54 UTC, merged