GAWB-1315 add PHI warning
broadinstitute/firecloud-ui pull request #599
Opened 2016-12-08 14:52 UTC by jlmwhitt

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-12-08 15:52 UTC, jmthibault79 commented
`Warning.svg` did not render for me.  Do you need to add it to a resource folder?

Since the two divs are identical, please define it in one place only.

2016-12-08 17:08 UTC, jlmwhitt commented
Added a component to common and use the component

2016-12-08 18:34 UTC, MattPutnam requested changes

2016-12-08 18:34 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
> +
This doesn't need to be a React component, it should just be a div, probably defined in common.  Also check indentation.

2016-12-08 18:34 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
> +    (when editing? [comps/PHIWarning])
Formatting.  The `]]` should go back on the previous line, and this isn't indented right.

2016-12-08 18:34 UTC, MattPutnam commented on src/static/assets/Warning.svg
> +<?xml version="1.0" ?><svg height="32px" version="1.1" viewBox="0 0 32 32" width="32px" xmlns="http://www.w3.org/2000/svg" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns:xlink="http://w
Can we just use the warning icon in icons.cljs?

2016-12-08 18:34 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs
> +      [comps/PHIWarning]
Do we need this one here?  This causes it to be shown twice in the import data dialog.

2016-12-08 20:20 UTC, jlmwhitt commented
Changed component to div from common, dropped the img and used the icon.

2016-12-08 21:49 UTC, jmthibault79 commented
👍

2016-12-08 21:53 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/common.cljs
> +    "FireCloud is not intended to host personally identifiable information. Do not use any patient identifier, including name, social security number, or medical record number."])
Nit: indentation

2016-12-08 21:54 UTC, MattPutnam commented on src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
> +          (do common/PHI-warning)
Don't need the `do`, just `common/PHI-warning`.  Same in the other place.

2016-12-09 13:44 UTC, jlmwhitt commented on src/cljs/org/broadinstitute/firecloud_ui/common.cljs
> +    "FireCloud is not intended to host personally identifiable information. Do not use any patient identifier, including name, social security number, or medical record number."])
Nit: document the style expected

2016-12-09 15:07 UTC, merged