iz GAWB-1293, GAWB-1294, GAWB-1295
broadinstitute/firecloud-ui pull request #610
Opened 2016-12-13 22:14 UTC by zarsky-broad

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-12-14 21:54 UTC, dmohs requested changes
Since I just touched this, lets have you rebase before I review.

2016-12-14 21:54 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/billing/create_project.cljs
> +             (js* "debugger;")
Whoops?

2016-12-15 15:28 UTC, dmohs requested changes

2016-12-15 15:28 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/billing/billing_management.cljs
> +                         (fn [{:keys [this]} scopes-needed]
This branch of the if statement does not work.

2016-12-15 15:28 UTC, dmohs commented on src/cljs/org/broadinstitute/firecloud_ui/page/billing/billing_management.cljs
> +                         (fn [{:keys [this]} scopes-needed]
Call this in your console to test:
```javascript
gapi.auth2.getAuthInstance().currentUser.get().disconnect()
```

2016-12-15 19:00 UTC, zarsky-broad commented on src/cljs/org/broadinstitute/firecloud_ui/page/billing/billing_management.cljs
> +                         (fn [{:keys [this]} scopes-needed]
I think this is fixed.

2016-12-19 20:42 UTC, dmohs approved these changes
Looks good to me, but I think this requires the following change in Rawls: https://github.com/broadinstitute/rawls/pull/601
@davidangb I think this would address the issue you pointed out to me in a previous PR.

2016-12-21 20:47 UTC, merged