GAWB-1519: "No billing project/account" related errors now contain a link to user guide on how to creat etheme
broadinstitute/firecloud-ui pull request #660
Opened 2017-02-08 15:07 UTC by MatthewBemis

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-02-08 16:09 UTC, zarsky-broad commented on src/cljs/main/broadfcui/common/components.cljs
> +                           (cond
This same cond is used twice, is it worth pulling it out into a `defn`?

2017-02-08 16:09 UTC, zarsky-broad commented on src/cljs/main/broadfcui/common/components.cljs
> +(defn push-error [content]
Why make this public?

2017-02-08 16:09 UTC, zarsky-broad commented on src/cljs/main/broadfcui/page/billing/create_project.cljs
> +                     :href "https://software.broadinstitute.org/firecloud/guide/topic?name=firecloud-google"} "here"] "."]
Bigger click targets are better; consider making both words of "click here" the link.

2017-02-08 16:09 UTC, zarsky-broad commented on src/cljs/main/broadfcui/page/workspace/create.cljs
> +                                           :href "https://software.broadinstitute.org/firecloud/guide/topic?name=firecloud-google"} "here"] "."]
See above.

2017-02-08 16:09 UTC, zarsky-broad commented on src/cljs/main/broadfcui/page/workspace/summary/tab.cljs
> +                                                      :href "https://software.broadinstitute.org/firecloud/guide/topic?name=firecloud-google"} "here"] "."]
See above; should this be a component, since it seems to happen repeatedly?

2017-02-09 19:25 UTC, dvoet requested changes
comments apply to both links

2017-02-09 19:25 UTC, dvoet commented on src/cljs/main/broadfcui/common/components.cljs
> +              :href "https://software.broadinstitute.org/firecloud/guide/topic?name=firecloud-google"} "click here"] "."])})
I feel like these URLs should be in config.

2017-02-09 19:25 UTC, dvoet commented on src/cljs/main/broadfcui/common/components.cljs
> +         " to create a new workspace. To learn how to create a billing project, ")
I think it is stronger text to have "Learn how to create a billing project" and have that be the link.

2017-02-09 19:32 UTC, MatthewBemis commented on src/cljs/main/broadfcui/common/components.cljs
> +         " to create a new workspace. To learn how to create a billing project, ")
i'll run that by a PO since this is what was in the story

2017-02-09 21:34 UTC, MatthewBemis commented
Updated to use url from config

See relevant firecloud-develop prs:

https://github.com/broadinstitute/firecloud-develop/pull/309
https://github.com/broadinstitute/firecloud-develop/pull/308

2017-02-14 14:36 UTC, dvoet approved these changes

2017-02-16 14:53 UTC, merged