[GAWB-1597] Switch position of name, namespace columns
broadinstitute/firecloud-ui pull request #722
Opened 2017-04-04 20:58 UTC by aednichols

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-04-04 21:06 UTC, MattPutnam requested changes

2017-04-04 21:06 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/method_repo/method_config_importer.cljs
> +                    (mapv (get item "method" {}) ["name" "namespace" "snapshotId"]))])}]))
This isn't for the name and namespace columns, this is for the "Referenced Method" column.

2017-04-04 21:09 UTC, davidangb commented on src/cljs/main/broadfcui/page/method_repo/method_config_importer.cljs
> +                    (mapv (get item "method" {}) ["name" "namespace" "snapshotId"]))])}]))
agreed - I think you only need the changes to the `Table {:columns ...`

2017-04-05 14:20 UTC, aednichols commented on src/cljs/main/broadfcui/page/method_repo/method_config_importer.cljs
> +                    (mapv (get item "method" {}) ["name" "namespace" "snapshotId"]))])}]))
Good call, saved us a bug:

![screen shot 2017-04-05 at 10 18 10 am](https://cloud.githubusercontent.com/assets/1087943/24709842/4548732c-19e9-11e7-8859-da2846f5b904.png)
vs.

![screen shot 2017-04-05 at 10 19 22 am](https://cloud.githubusercontent.com/assets/1087943/24709888/5d01473c-19e9-11e7-82c4-c9667e7c0abf.png)

2017-04-05 14:43 UTC, davidangb approved these changes
👍 code looks good; I did not test!

2017-04-05 18:43 UTC, MattPutnam approved these changes

2017-04-06 15:19 UTC, merged