GAWB-1406: Workspace filter overhaul
broadinstitute/firecloud-ui pull request #728
Opened 2017-04-10 19:15 UTC by MattPutnam

Also fixes an untracked bug introduced in the table refactor--restoring the text of filter fields.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-04-11 20:01 UTC, davidangb requested changes
Some comments inline. Also, from testing this myself:
* if I enter some characters into the tag control, I always get a first suggestion of "undefined"
* selecting Published=published finds 86 workspaces, even though library reindex only finds 83 workspaces. I don't know why this is happening.
* the text filter updates the pagination control to say e.g. "1 - 20 of 72 results (filtered from 2803 total)" ... should the filters do the same? The previous filter did not, but with the UX changing, PO might want this ...
* I'm surprised PO hasn't asked to add a Tags column to the table.
* if I add a tag as a filter, then reload the page - or switch to library and then back to workspaces - the tag filter _is_ properly initialized with my previous tag. However, if I use the delete key to remove that tag, instead of removing the tag, the control changes the tag "badge" into plain text.
* upon first load (or after clearing local storage), the Access Level column of the table is scrolled off the right side of the page for me.

2017-04-11 20:01 UTC, davidangb commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +        {:ref "table" :persistence-key "workspace-table" :v 2
use `:v VERSION` instead?

2017-04-11 20:01 UTC, davidangb commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +                           "Project Owner"
use `prettify` instead?

2017-04-11 20:01 UTC, davidangb commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +          :on-clear #((@refs "tag-autocomplete") :set-tags [])})
in the workspace listing, the tag autocomplete control should use the set of tags returned *on the list of workspaces for the current user*, not the set of tags returned from /api/workspaces/tags.

2017-04-11 20:20 UTC, davidangb commented
I found the issue with the UI filter finding 86 published workspaces, where the backend Scala filter only finds 83. There are three workspaces - including broad-dsde-dev/GAWB-616-failedWorkflows which you are an owner of - that have a `library:published` attribute with a _string_ value of "true". The UI filter finds these, whereas Scala does not.

2017-04-11 20:36 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +        {:ref "table" :persistence-key "workspace-table" :v 2
There are two versions here: the page, and the table (and I just noticed that the page persistence key is still "workspace-table-types" -- do we want to do something about that?).  We could tie them together for clarity though.

2017-04-11 20:40 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +          :on-clear #((@refs "tag-autocomplete") :set-tags [])})
Is that going to be a new orch endpoint?

2017-04-11 20:47 UTC, rushtong commented on src/cljs/main/broadfcui/page/workspaces_list.cljs
> +          :on-clear #((@refs "tag-autocomplete") :set-tags [])})
David's understanding was mine as well ... sum up all of the tags in each of the workspaces returned from the workspace list and use that as the universe of autocomplete tags when filtering workspaces.

2017-04-11 20:56 UTC, rushtong commented
Generic comment on pagination:
* Navigate to any page > 1 in your workspace list
* Check some facet (published in my case) that limits the known list to less than the number displayed per page.
* The behavior is confusing. All rows go away, a message with `There are no rows to display.`, but you can navigate back to page 1 and see the rows. 

Can we drop the pagination to something that makes sense when the results get filtered?

2017-04-11 21:09 UTC, rushtong commented
**Tag-list reloading strangeness.** I don't know if this is our library working the way it does, or something else, but the effect is confusing.
* Enter a tag into the text box 
* Immediately delete without moving the mouse (using the delete key)
* I get a message in the drop down, "The results could not be loaded"

That error persists for some variable number of seconds if I don't move the mouse or click out of the text box. Sometimes it refreshes almost immediately, sometimes for many seconds. Clicking outside the box, then back in again will trigger an immediate refresh.

2017-04-11 21:22 UTC, rushtong requested changes
I don't have any code feedback, just functionality suggestions in other comments.

2017-04-12 20:55 UTC, rushtong approved these changes
👍 LG, WG!

2017-04-12 21:48 UTC, davidangb commented
Code looks good and works as expected. 👍 on the code level.

I have UX concerns - which really isn't my department, but here goes:
* I love the redesign of namespace/name!
* The tag control allows you to enter arbitrary tags - including tags that don't exist. This doesn't make sense in terms of the tag control.
* By default (i.e. after clearing local storage), the Workspace column is cut off, but the Access Level column has lots of extra whitespace. The Description column also has whitespace - I think this could be optimized. If you need to shrink, I bet you could drop the font size just a little.
* I think the text filter control should be moved into the grey section of the left column, same way it works in Library. I realize this complicates the hide/show filters feature. Personally, I'd be fine always showing the filters.

2017-04-12 21:49 UTC, davidangb reviewed
added UX feedback. Attempting to change this review from "Request Changes" to "Comment".

2017-04-19 18:24 UTC, davidangb approved these changes
👍 for code, did not test

2017-04-19 21:13 UTC, merged