GAWB-1819: Show service alerts based on bucket contents
broadinstitute/firecloud-ui pull request #731
Opened 2017-04-11 19:50 UTC by MatthewBemis

Relies on some scripts and config changes that will go into firecloud-develop shortly

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-04-11 19:50 UTC, MatthewBemis commented on src/cljs/main/broadfcui/main.cljs
> +     (utils/ajax {:url "http://storage.googleapis.com/firecloud-alerts-dev/alerts.json"
I have this in config but there's some sort of race condition where it's not loaded in time so I need to solve that before I use the config'd version

2017-04-12 14:46 UTC, dvoet commented on src/cljs/main/broadfcui/main.cljs
> +     (utils/ajax {:url (config/alerts-json-url)
what happens when the file can't be downloaded due to an error? Can/should we show a generic connectivity warning?

2017-04-12 17:12 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +     (utils/ajax {:url (config/alerts-json-url)
I'm hesitant to show an error that we can't tell if there's an error...

2017-04-12 17:22 UTC, zarsky-broad requested changes

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/common/icons.cljs
> +     (icon {:style (merge {:color "white" :fontSize (:size props)} props)} :warning-triangle))})
I suspect this may not be what you really want to do. Why merge this in if `:size` is already being pulled from it?

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/config.cljs
> +                  "callCachingGuideUrl" :string "alertsJsonUrl" :string}
Are we sure this should be optional?

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +    [icons/ExceptionIcon {:size 18 :paddingRight "0.5rem"}] (if title title "Service Alert")]
Why not simply put the `:paddingRight` on the containing div?

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +    [:div {} (str message " ")
Why add another div here?

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +       (when (not (empty? alerts))
```cljs
(when-let [alerts (not-empty (:alerts @state))]
...
```

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +                               (if (not (empty? parsed))
Should this be a `when`?

See comment above on `when-let`, otherwise `if-let` exists too.

2017-04-12 17:22 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +(react/defc ShowStatusAlerts
I'd say this is less `ShowStatusAlerts` and more, I dunno, `StatusAlertContainer` or something like that.

2017-04-12 17:25 UTC, MatthewBemis commented on src/cljs/main/broadfcui/common/icons.cljs
> +     (icon {:style (merge {:color "white" :fontSize (:size props)} props)} :warning-triangle))})
correct I think i want

`
 (icon {:style (merge {:color "white"} props)} :warning-triangle))})
`

2017-04-12 17:25 UTC, MatthewBemis commented on src/cljs/main/broadfcui/config.cljs
> +                  "callCachingGuideUrl" :string "alertsJsonUrl" :string}
I don't even know why any of these are optional tbh, they all seem equally important

2017-04-12 17:26 UTC, MatthewBemis commented on src/cljs/main/broadfcui/main.cljs
> +    [icons/ExceptionIcon {:size 18 :paddingRight "0.5rem"}] (if title title "Service Alert")]
I want the padding to be between the icon and the title text, wouldn't that just put the padding on that entire unit?

2017-04-12 17:26 UTC, zarsky-broad commented on src/cljs/main/broadfcui/common/icons.cljs
> +     (icon {:style (merge {:color "white" :fontSize (:size props)} props)} :warning-triangle))})
I don't think you want to change this line at all. See my comment where you're using this below.

2017-04-12 17:27 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +    [icons/ExceptionIcon {:size 18 :paddingRight "0.5rem"}] (if title title "Service Alert")]
Ah, I see. The way we've been dealing with that is to wrap the icon in its own container.

2017-04-12 17:35 UTC, MatthewBemis commented on src/cljs/main/broadfcui/main.cljs
> +       (when (not (empty? alerts))
whoa this is \~cool\~

2017-04-12 17:39 UTC, dvoet commented on src/cljs/main/broadfcui/main.cljs
> +     (utils/ajax {:url (config/alerts-json-url)
how about this: as with all google calls, we should retry with exponential backoff and if we are still failing we should display a "There may be a problems accessing google cloud storage" and give them a link to https://status.cloud.google.com/

2017-04-12 17:39 UTC, dvoet commented
should we be polling periodically to get this warning?

2017-04-12 17:40 UTC, zarsky-broad commented
Yeah, we'd discussed doing that, like how we poll queue status...

2017-04-12 17:40 UTC, dvoet commented
and decided not to?

2017-04-12 17:41 UTC, zarsky-broad commented
Nope, I think we were going to

2017-04-12 17:41 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +     (utils/ajax {:url (config/alerts-json-url)
Works for me!

2017-04-12 17:48 UTC, MatthewBemis commented on src/cljs/main/broadfcui/main.cljs
> +    [:div {} (str message " ")
i don't actually know anything about styling and positioning so i just end up putting divs everywhere ¯\_(ツ)_/¯

2017-04-12 17:50 UTC, MatthewBemis commented on src/cljs/main/broadfcui/config.cljs
> +                  "callCachingGuideUrl" :string "alertsJsonUrl" :string}
(for the record I'm not going to change it until I figure out why things that are way more important such as `shibbolethUrlRoot` are in the optional section)

2017-04-12 17:51 UTC, MatthewBemis commented
I'll add polling but that was never discussed with me until this very moment

2017-04-12 19:56 UTC, zarsky-broad commented on src/cljs/main/broadfcui/main.cljs
> +    [:div {} (str message " ")
Don't think about it in terms of styling or positioning here. It's just an extraneous level of container.

2017-04-12 20:06 UTC, zarsky-broad commented
I def forgot that we'd talked about it, so that may be on me?

2017-04-13 15:38 UTC, zarsky-broad approved these changes

2017-04-14 15:24 UTC, dvoet approved these changes

2017-04-21 18:27 UTC, merged