[GAWB-2156] Cannot Launch Analysis on entity of type X if its ID is hidden in the Data tab
broadinstitute/firecloud-ui pull request #818
Opened 2017-06-05 18:56 UTC by rtitle

See: https://broadinstitute.atlassian.net/browse/GAWB-2156

Summary:
- Made the `entity-column` of `EntityTable` non reorderable. This means it can't be hidden via the Filter Columns dialog. This applies to all instances of the `EntityTable` component.
- In the Launch Analysis modal, made it so you can click _anywhere_ in the table row to select an entity.
- In the Launch Analysis modal, made the entity column not a link. 

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-06-05 21:03 UTC, rtitle commented
@MattPutnam want to take a look at this for me? Thanks.

2017-06-06 16:36 UTC, MattPutnam requested changes

2017-06-06 16:36 UTC, MattPutnam commented on src/cljs/main/broadfcui/common/table_utils.cljs
> +                                     {:onMouseDown (fn [] (on-row-click (first row)))}))]
`:on-row-click` should take the whole row, and probably the index, like row-style does.

2017-06-06 16:36 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/workspace/method_configs/launch_analysis.cljs
> +      :on-row-click (fn [e]
`e` is for event objects, so call this `row`.

2017-06-06 19:11 UTC, rtitle commented
Thanks @MattPutnam, pushed a commit with changes.

2017-06-07 15:37 UTC, MattPutnam approved these changes
👍 with some cosmetic comments

2017-06-07 15:37 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/workspace/method_configs/launch_analysis.cljs
>                        :else "#fff")})
Stick a `:cursor "pointer"` in here so rows look clickable

2017-06-07 15:37 UTC, MattPutnam commented on src/cljs/main/broadfcui/page/workspace/method_configs/launch_analysis.cljs
> +                            entity-id (entity->id row)]
Rename `row` to `entity`, and `row-data` to `row`.  You can also rename `row-index` to `_` to indicate it's unused (and it gets rid of an editor warning for me at least).

2017-06-07 15:37 UTC, MattPutnam commented on src/cljs/main/broadfcui/common/table_utils.cljs
> +                  row-style (-> props (:row-style) (get-row-style) (merge {:display "flex" :alignItems "center"}))
Minor style thing: you can omit the parens around single entries in a threading macro.  So just `(-> props :row-style get-row-style ...)`.

2017-06-07 18:53 UTC, rtitle commented on src/cljs/main/broadfcui/page/workspace/method_configs/launch_analysis.cljs
>                        :else "#fff")})
Neat

2017-06-07 18:57 UTC, rtitle commented
Made cosmetic changes

2017-06-07 19:43 UTC, merged