GAWB-2104: Split "Public" and "My" Workspaces
broadinstitute/firecloud-ui pull request #906
Opened 2017-08-15 20:39 UTC by MattPutnam

Also did some work to use the new tabs everywhere, and make the 3 main pages look the same.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-08-17 11:07 UTC, rushtong commented
When first navigating to the Method Repository, none of the sub-tabs were selected. The "All (XX)" should have been, but wasn't. Selecting any tab seems to reset the behavior correctly so that it will navigate to the right one on subsequent reloads. I'm guessing this has to do with local storage, but even after deleting my local storage, I could not replicate the original, unselected sub-tab condition.

2017-08-17 11:11 UTC, rushtong commented
This needs a rebase, especially to pull in the shield-icon fix.

2017-08-17 11:51 UTC, rushtong commented
For the jira ticket, please list each of the modified pages that need to be QA-ed in the QA section since the changes are more in-depth than the story originally describes.

2017-08-17 12:04 UTC, rushtong commented
I'm confused by the counts that show in the workspaces tab when a filter is applied. In my example, I have 22 "My" workspaces and 23 "Public" workspaces. Applying a filter that reduces the number displayed to a single one looks strange. The "My" is empty, but shows a count of 22. The "Public" has 1, but shows a count of 23. Logically, I know that the counts are not reflected in the filter, but the visual effect is off. For example, if I leave that filter in place, leave, come back, and see the page again, it takes a split-second to realize what's happening.

Suggestion: I think the counts should update to reflect the filtered effect. Something like "My Workspaces (0 visible of 22 total)". I think this might also require PO feedback.

![screen shot 2017-08-17 at 8 03 07 am](https://user-images.githubusercontent.com/116679/29411380-93b74018-8322-11e7-9992-8042850741ff.png)

2017-08-17 12:20 UTC, rushtong commented
In the condition where there are no rows in a table, the alignment of the background color block with the tabs is now more apparent when the tabs didn't have a background and now looks jagged. Is it possible to align these? Not a big deal, but I think it would be cleaner if the right edge of the empty table aligned with the right edge of the tabs block. Screenshot shows old over the new.

![screen shot 2017-08-17 at 8 17 09 am](https://user-images.githubusercontent.com/116679/29411979-e71b33ac-8324-11e7-9c1d-6fbb766222a7.png)

2017-08-17 12:48 UTC, rushtong requested changes
Overall, looks really good! 
* I have one request about counts that I think should be addressed in some way.
* My request for table alignment is minor - don't let that hold things up.

2017-08-17 12:48 UTC, rushtong commented on src/cljs/main/broadfcui/page/method_repo/method_config_importer.cljs
> +                  {:data-test-id (config/when-debug (str name "_" snapshotId))
I think this is used for test automation - is that right?

2017-08-18 18:50 UTC, ahaessly commented on src/cljs/main/broadfcui/page/method_repo/method_config_importer.cljs
> +                  {:data-test-id (config/when-debug (str name "_" snapshotId))
yes, it is

2017-08-18 18:50 UTC, ahaessly approved these changes
👍

2017-08-18 19:00 UTC, ahaessly commented
saw a minor issue - if the browser is resized to something narrow the table on the launch analysis screen extends past the boundary
![screen shot 2017-08-18 at 2 59 17 pm](https://user-images.githubusercontent.com/22915781/29473489-f9b2c8c0-8425-11e7-9274-906ee6d6126f.png)

2017-08-18 20:21 UTC, rushtong approved these changes

2017-08-18 20:29 UTC, merged