Jr prod smoketests
broadinstitute/firecloud-ui pull request #968
Opened 2017-09-28 19:54 UTC by jacmrob

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-09-28 20:05 UTC, jacmrob commented
jenkins retest

2017-09-29 19:49 UTC, breilly2 requested changes
Sorry... not done yet, but here's some initial feedback... including one that definitely needs to be done.

2017-09-29 19:49 UTC, breilly2 commented on automation/docker/application.conf.ctmpl
> +  orchApiUrl = "https://firecloud-orchestration.dsde-prod.broadinstitute.org/"
This can be https://api.firecloud.org/ which is both easier to read and probably what consumers are using (or should be using).

2017-09-29 19:49 UTC, breilly2 commented on automation/docker/application.conf.ctmpl
> +{{if eq $environment "prod"}}
There are already `$environment` checks inside the `fireCloud` block. Can the prod checks be pushed inside, or the others be pulled out? I think it would help readability and maintainability to have them all part of one logical block.

2017-09-29 19:49 UTC, breilly2 commented on automation/docker/application.conf.ctmpl
> +  {{if eq $environment "prod"}}appsDomain = "firecloud.org"{{else}}appsDomain = {{if eq $environment "qa"}}"quality.firecloud.org"{{else}}"{{$environment}}.test.firecloud.org"{{end}}{{end}}
Similarly, this can be:
```
  appsDomain = "{{if eq $environment "prod"}}firecloud.org{{else if eq $environment "qa"}}quality.firecloud.org{{else}}{{$environment}}.test.firecloud.org{{end}}"
```

2017-09-29 19:49 UTC, breilly2 commented on automation/docker/application.conf.ctmpl
> +  smoketestpassword = {{if eq $environment "prod"}}"{{$users.Data.users_passwd}}"{{else}}"alohomora"{{end}}
Password needs to be read from vault. It should always be there no matter what `$environment` is.

2017-09-29 20:24 UTC, ahaessly reviewed
a few comments. i can help with some of the refactoring if you want

2017-09-29 20:24 UTC, ahaessly commented on automation/docker/application.conf.ctmpl
> +{{else}}
i think we maybe we should refactor the blocks below to help understand the different cases

2017-09-29 20:24 UTC, ahaessly commented on automation/docker/application.conf.ctmpl
> +  {{if eq $environment "prod"}}appsDomain = "firecloud.org"{{else}}appsDomain = {{if eq $environment "qa"}}"quality.firecloud.org"{{else}}"{{$environment}}.test.firecloud.org"{{end}}{{end}}
maybe use:
appsDomain = {{if eq $environment "prod"}}"firecloud.org"{{else if eq $environment "qa"}}"quality.firecloud.org"{{else}}"{{$environment}}.test.firecloud.org"{{end}}

2017-09-29 20:24 UTC, ahaessly commented on automation/render-local-env.sh
> +VAULT_TOKEN=$
is this change a mistake?

2017-09-29 20:24 UTC, ahaessly commented on automation/run-smoketests.sh
> +./run-tests.sh 4 ${ENV} ${ENV} automation ${VAULT_TOKEN}
i think we could merge this run-tests-on-alpha (but rename)

2017-10-02 18:45 UTC, jacmrob commented on automation/render-local-env.sh
> +VAULT_TOKEN=$
yep thanks

2017-10-02 20:32 UTC, breilly2 approved these changes
Only one minor nit. Otherwise 👍

2017-10-02 20:32 UTC, breilly2 commented on automation/src/test/scala/org/broadinstitute/dsde/firecloud/test/e2e/SmoketestSpec.scala
> +    assert(workspaceDataTab.getNumberOfParticipants() == 1)
Tests should use `should` expressions instead of asserts (there may be bad examples in our existing tests). This should be:
```
    workspaceDataTab.getNumberOfParticipants() shouldEqual 1
```

2017-10-03 19:59 UTC, merged